DROP TABLE IF EXISTS TX_DENDA_KETERLAMBATAN;

CREATE TABLE TX_DENDA_KETERLAMBATAN(
    denda_id VARCHAR(10) PRIMARY KEY NOT NULL,
    no_transaksi VARCHAR(15) NOT NULL,
    cicilan_ke INT4 NOT NULL,
    tgl_denda TIMESTAMP NOT NULL,
    biaya_denda NUMERIC(10,2) NOT NULL,
    tgl_pembayaran_denda TIMESTAMP NULL,
    no_pembayaran VARCHAR(20) NULL
) WITH (
    OIDS=FALSE
);

SELECT * FROM TX_DENDA_KETERLAMBATAN;